@baseUrl = http://localhost:8080

### Criar usuário (obter o ID da resposta)
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "João da Silva",
  "email": "joao@example.com"
}

### Criar leilão (copie o ID da resposta)
POST {{baseUrl}}/auction
Content-Type: application/json

{
  "product_name": "PlayStation 5",
  "category": "Games",
  "description": "Console novo, lacrado",
  "condition": 1
}

### Criar lance
POST {{baseUrl}}/bid
Content-Type: application/json

{
  "auction_id": "42f9cad4-d05e-46ba-9828-6e3e29916703",
  "user_id": "5c1926b1-db65-45f3-8808-717e1aa0116f",
  "amount": 600.00
}

### Verificar o lance vencedor
GET {{baseUrl}}/auction/winner/42f9cad4-d05e-46ba-9828-6e3e29916703
Content-Type: application/json
